site_name: QuBLAS

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  # - pymdownx.emoji:
  #  emoji_index: !!python/name:material.extensions.emoji.twemoji
  #  emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      # permalink: true
      # title: On this page
      # permalink_title: Anchor link to this section for reference
      toc_depth: 1
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

    annotation: material/circle-medium

  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - header.autohide
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune

extra_css:
  - scripts/style.css

extra_javascript:
  - scripts/style.js
